// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package account_db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AccountNotificationSetting struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	SendEmail             sql.NullBool
	SendPushNotifications sql.NullBool
	CreatedAt             sql.NullTime
	UpdatedAt             sql.NullTime
	DeletedAt             sql.NullTime
	IsArchived            sql.NullBool
}

type AccountProfile struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	UserName   string
	AvatarUrl  sql.NullString
	CreatedAt  time.Time
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
	IsArchived sql.NullBool
}
