// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package account_db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type AccountContactInformation struct {
	ID                     uuid.UUID
	ProfileID              uuid.NullUUID
	ContactInformationType sql.NullString
	IsPublic               sql.NullBool
	ContactInformation     sql.NullString
	CreatedAt              sql.NullTime
	UpdatedAt              sql.NullTime
	DeletedAt              sql.NullTime
	IsArchived             sql.NullBool
}

type AccountProfile struct {
	ID         uuid.UUID
	UserName   string
	AvatarUrl  sql.NullString
	CreatedAt  time.Time
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
	IsArchived sql.NullBool
}
