// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profile.sql

package account_db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createProfile = `-- name: CreateProfile :exec
INSERT INTO account.profile (id, user_id, user_name, avatar_url, created_at, is_archived)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type CreateProfileParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	UserName   string
	AvatarUrl  sql.NullString
	CreatedAt  time.Time
	IsArchived sql.NullBool
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.ExecContext(ctx, createProfile,
		arg.ID,
		arg.UserID,
		arg.UserName,
		arg.AvatarUrl,
		arg.CreatedAt,
		arg.IsArchived,
	)
	return err
}
